<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-CGUB1Q1" name="com.ChrisMensing.AmazonSeleniumFramework.VerifySignIn" tests="4" failures="1" timestamp="2019-09-10T19:04:58 EDT" time="73.836" errors="3">
  <testcase name="SignInTest" time="0.011" classname="com.ChrisMensing.AmazonSeleniumFramework.VerifySignIn">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.ChrisMensing.AmazonSeleniumFramework.base.WedDriverBuilder.<init>(WedDriverBuilder.java:23)
at com.ChrisMensing.AmazonSeleniumFramework.PageObjects.PageSuper.GetDriver(PageSuper.java:32)
at com.ChrisMensing.AmazonSeleniumFramework.PageObjects.HomePage.<init>(HomePage.java:20)
at com.ChrisMensing.AmazonSeleniumFramework.VerifySignIn.SignInTest(VerifySignIn.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- SignInTest -->
  <testcase name="SignInTest" time="0.011" classname="com.ChrisMensing.AmazonSeleniumFramework.VerifySignIn">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.ChrisMensing.AmazonSeleniumFramework.base.WedDriverBuilder.<init>(WedDriverBuilder.java:23)
at com.ChrisMensing.AmazonSeleniumFramework.PageObjects.PageSuper.GetDriver(PageSuper.java:32)
at com.ChrisMensing.AmazonSeleniumFramework.PageObjects.HomePage.<init>(HomePage.java:20)
at com.ChrisMensing.AmazonSeleniumFramework.VerifySignIn.SignInTest(VerifySignIn.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- SignInTest -->
  <testcase name="SignInTest" time="73.803" classname="com.ChrisMensing.AmazonSeleniumFramework.VerifySignIn">
    <failure type="java.lang.AssertionError" message="did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.ChrisMensing.AmazonSeleniumFramework.PageObjects.SignInPage.SignIn(SignInPage.java:71)
at com.ChrisMensing.AmazonSeleniumFramework.VerifySignIn.SignInTest(VerifySignIn.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- SignInTest -->
  <testcase name="SignInTest" time="0.011" classname="com.ChrisMensing.AmazonSeleniumFramework.VerifySignIn">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.ChrisMensing.AmazonSeleniumFramework.base.WedDriverBuilder.<init>(WedDriverBuilder.java:23)
at com.ChrisMensing.AmazonSeleniumFramework.PageObjects.PageSuper.GetDriver(PageSuper.java:32)
at com.ChrisMensing.AmazonSeleniumFramework.PageObjects.HomePage.<init>(HomePage.java:20)
at com.ChrisMensing.AmazonSeleniumFramework.VerifySignIn.SignInTest(VerifySignIn.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- SignInTest -->
</testsuite> <!-- com.ChrisMensing.AmazonSeleniumFramework.VerifySignIn -->
